### ISSUE TITLE
Change Ship - Choose ship can be clicked multiple times; decrementing XP each time.

### ISSUE THREAD

**Issue by bdwakefield** [grahamgilchrist/hotac-squad-builder#126] opened 2017-11-08 00:35 UTC
Add a bunch of XP and level up the pilot to PS4. Select [Change Ship]. Choose a ship and and click [Choose Ship] multiple times. Observe current XP continue to decrease into the negative.
![image](https://user-images.githubusercontent.com/3208406/32525512-cd4695ac-c3f2-11e7-9e30-6ee3f0851a30.png)

**Comment by grahamgilchrist** [comment] 2017-11-08 16:55
Hmm the button should grey out and be disabled when you don't have enough Xp or are lower than PS4

I can't reproduce this.

Could you provide a few more details. Browser/device/OS version, and maybe some screenshots of the steps?

**Comment by grahamgilchrist** [comment] 2017-11-08 22:51
Hmm wait now I can reproduce this. wierd. will take a look

**Comment by grahamgilchrist** [comment] 2017-11-08 22:55
Ok right, sorry. i was working in another branch where I had already fixed this issue. 

Fixed in #133

**Closed by grahamgilchrist** 2017-11-08 22:55 UTC
Labels: Blocked, bug, Needs more information

**Comment by bdwakefield** [comment] 2017-11-08 23:59
Sweet!
